using System.Collections.Generic;
using System.Linq;
using SigQL.Types.Attributes;

namespace SigQL.Tests.Common.Databases.Labor
{
    /// <summary>
    /// A service a custom repository method depends on, supplied by the configured service resolver.
    /// </summary>
    public interface IWorkLogSummarizer
    {
        string Summarize(IEnumerable<WorkLog.IWorkLogId> workLogs);
    }

    public class WorkLogSummarizer : IWorkLogSummarizer
    {
        public string Summarize(IEnumerable<WorkLog.IWorkLogId> workLogs)
        {
            return $"summarized {workLogs.Count()}";
        }
    }

    /// <summary>
    /// Mixes generated methods with methods that supply their own implementation.
    /// </summary>
    public interface ICustomImplementationRepository
    {
        // generated by SigQL
        IEnumerable<WorkLog.IWorkLogId> GetAllIds();
        WorkLog.IWorkLogId GetById(int id);

        // a custom body that composes a generated method
        int CountAllIds() => GetAllIds().Count();

        // a custom body with an injected service; callers write SummarizeAll()
        string SummarizeAll([Inject] IWorkLogSummarizer summarizer = null) =>
            summarizer.Summarize(GetAllIds());

        // an injected service exposed as a property, invisible at the call site
        [Inject]
        IWorkLogSummarizer Summarizer { get; }

        string SummarizeViaProperty() => Summarizer.Summarize(GetAllIds());

        // ordinary parameters and injected ones together
        string SummarizeOne(int id, [Inject] IWorkLogSummarizer summarizer = null) =>
            summarizer.Summarize(new[] { GetById(id) });
    }

    /// <summary>
    /// The motivating case: a one-off custom query written inline, alongside generated methods,
    /// without introducing a class.
    /// </summary>
    public interface IRawQueryRepository
    {
        IEnumerable<WorkLog.IWorkLogId> GetAllIds();

        IEnumerable<WorkLog.IWorkLogId> GetIdsAbove(int minimumId, [Inject] IQueryMaterializer materializer = null) =>
            materializer.Materialize<IEnumerable<WorkLog.IWorkLogId>>(
                "select Id from WorkLog where Id > @minimumId", new { minimumId });
    }

    /// <summary>
    /// An [Inject] parameter with no default value, which would force callers to supply it.
    /// </summary>
    public interface IInvalidInjectRepository
    {
        string SummarizeAll([Inject] IWorkLogSummarizer summarizer) =>
            summarizer.Summarize(new List<WorkLog.IWorkLogId>());
    }

    /// <summary>
    /// The same mix expressed as an abstract class, where custom methods are virtual.
    /// </summary>
    public abstract class CustomImplementationAbstractRepository
    {
        public abstract IEnumerable<WorkLog.IWorkLogId> GetAllIds();

        public virtual int CountAllIds() => GetAllIds().Count();

        public virtual string SummarizeAll([Inject] IWorkLogSummarizer summarizer = null) =>
            summarizer.Summarize(GetAllIds());
    }
}
