using System.Collections.Generic;
using System.Linq;
using SigQL.Types.Attributes;

namespace SigQL.Tests.Common.Databases.Labor
{
    /// <summary>
    /// The interface callers depend on, where the implementation lives on an abstract class. Custom
    /// bodies only run when the proxy is built for the class, so resolving this interface has to
    /// map to <see cref="WorkLogInterfacedRepository"/> rather than to an interface proxy.
    /// </summary>
    public interface IWorkLogInterfacedRepository
    {
        IEnumerable<WorkLog.IWorkLogId> GetAllIds();
        string Describe();
        int CountAllIds();
        IEnumerable<WorkLog.IWorkLogId> GetIdsAbove(int minimumId, [Inject] IQueryMaterializer materializer = null);
    }

    public abstract class WorkLogInterfacedRepository : IWorkLogInterfacedRepository
    {
        // generated by SigQL
        public abstract IEnumerable<WorkLog.IWorkLogId> GetAllIds();

        // a custom body that touches no database at all
        public virtual string Describe() => "custom implementation";

        // a custom body that composes a generated method
        public virtual int CountAllIds() => GetAllIds().Count();

        // a custom body running its own SQL, with the materializer injected
        public virtual IEnumerable<WorkLog.IWorkLogId> GetIdsAbove(int minimumId, [Inject] IQueryMaterializer materializer = null)
        {
            return materializer.Materialize<IEnumerable<WorkLog.IWorkLogId>>(
                "select Id from WorkLog where Id > @minimumId", new { minimumId });
        }
    }
}
