name: Push release packages to Nuget.org

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    env:
      Configuration: Release
      
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=version::$(cat version.txt)"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      env:
        PACKAGE_VERSION: '${{ steps.vars.outputs.version }}'
      run: dotnet pack /p:Version=${{ env.PACKAGE_VERSION }}
    - name: Push
      run: dotnet nuget push "**/SigQL*.nupkg" -k ${{ secrets.NUGET_ORG_KEY }} -s https://api.nuget.org/v3/index.json
      
