name: .NET

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    env:
      PACKAGE_BASE_VERSION: 0.0.1
      GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
      VERSIONDATE: $(date +'%Y%m%d')
      VERSION: $PACKAGE_BASE_VERSION-CI-$VERSIONDATE-$GIT_HASH
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Show version
      run: echo "${{ env.VERSION }}"
    - name: Pack
      run: dotnet pack /p:Version=${{ env.VERSION }}
    - name: Push
      run: dotnet nuget push "**/SigQL.nupkg" -k ${{ secrets.NUGET_ORG_KEY }} -s https://api.nuget.org/v3/index.json
      
